all:
	(cd timerLib && make install)
	(cd blink_proj && make)
	(cd button_proj && make)
	(cd buzzer_proj && make)

clean:
	(cd timerLib && make clean)
	(cd blink_proj && make clean)
	(cd button_proj && make clean)
	(cd buzzer_proj && make clean)

